DROP TABLE IF EXISTS users,pet;
CREATE TABLE users(
id BIGINT PRIMARY KEY AUTO_INCREMENT,
 name VARCHAR2(256),
 age VARCHAR2(256),
 pet_id BIGINT
);

CREATE TABLE pet(
id BIGINT PRIMARY KEY AUTO_INCREMENT,
breed VARCHAR2(256)
);
ALTER TABLE users add FOREIGN KEY (pet_id) REFERENCES pet(id);
